export const LOAD_ACCOUNTS_REQUEST = 'Account/LOAD_ACCOUNTS_REQUEST';
export const LOAD_ACCOUNTS_SUCCESS = 'Account/LOAD_ACCOUNTS_SUCCESS';

export const CREATE_ACCOUNTS_REQUEST = 'Account/CREATE_ACCOUNTS_REQUEST';
export const CREATE_ACCOUNTS_SUCCESS = 'Account/CREATE_ACCOUNTS_SUCCESS';

export const UPDATE_ACCOUNTS_REQUEST = 'Account/UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNTS_SUCCESS = 'Account/UPDATE_ACCOUNTS_SUCCESS';

export const DELETE_ACCOUNTS_REQUEST = 'Account/DELETE_ACCOUNTS_REQUEST';
export const DELETE_ACCOUNTS_SUCCESS = 'Account/DELETE_ACCOUNTS_SUCCESS';